<?php
namespace App\Controller;
use Cake\Event\Event;

use App\Controller\AppController;

/**
 * Publications Controller
 *
 * @property \App\Model\Table\PublicationsTable $Publications
 *
 * @method \App\Model\Entity\Publication[]|\Cake\Datasource\ResultSetInterface paginate($object = null, array $settings = [])
 */
class PublicationsController extends AppController
{
    public function beforeFilter(Event $event)
    {
        $this->viewBuilder()->setLayout('forum');
        return parent::beforeFilter($event); // TODO: Change the autogenerated stub
    }
    /**
     * Index method
     *
     * @return \Cake\Http\Response|void
     */
    public function index()
    {

        $publications = $this->paginate($this->Publications->find()
            ->contain(['Photos', 'TypeOfPublications','Users','Tgroups'])


        );



        $this->set(compact('publications'));
    }


    /**
     * View method
     *
     * @param string|null $id Publication id.
     * @return \Cake\Http\Response|void
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function view($id = null)
    {
        $publication = $this->Publications->get($id, [
            'contain' => ['Photos', 'TypeOfPublications', 'Users', 'Tgroups']
        ]);

        $this->set('publication', $publication);
    }

    /**
     * Add method
     *
     * @return \Cake\Http\Response|null Redirects on successful add, renders view otherwise.
     */
    public function add()
    {
        $publication = $this->Publications->newEntity();
        if ($this->request->is('post')) {
            $publication = $this->Publications->patchEntity($publication, $this->request->getData());
            if ($this->Publications->save($publication)) {
                $this->Flash->success(__('The publication has been saved.'));

                return $this->redirect(['action' => 'index']);
            }
            $this->Flash->error(__('The publication could not be saved. Please, try again.'));
        }
        $photos = $this->Publications->Photos->find('list', ['limit' => 200]);
        $typeOfPublications = $this->Publications->TypeOfPublications->find('list', ['limit' => 200]);
        $users = $this->Publications->Users->find('list', ['limit' => 200]);
        $categories = $this->Publications->Categories->find('list', ['limit' => 200]);
        $tgroups = $this->Publications->Tgroups->find('list', ['limit' => 200]);
        $this->set(compact('publication', 'photos', 'typeOfPublications', 'users', 'categories', 'tgroups'));
    }

    /**
     * Edit method
     *
     * @param string|null $id Publication id.
     * @return \Cake\Http\Response|null Redirects on successful edit, renders view otherwise.
     * @throws \Cake\Network\Exception\NotFoundException When record not found.
     */
    public function edit($id = null)
    {
        $publication = $this->Publications->get($id, [
            'contain' => []
        ]);
        if ($this->request->is(['patch', 'post', 'put'])) {
            $publication = $this->Publications->patchEntity($publication, $this->request->getData());
            if ($this->Publications->save($publication)) {
                $this->Flash->success(__('The publication has been saved.'));

                return $this->redirect(['action' => 'index']);
            }
            $this->Flash->error(__('The publication could not be saved. Please, try again.'));
        }
        $photos = $this->Publications->Photos->find('list', ['limit' => 200]);
        $typeOfPublications = $this->Publications->TypeOfPublications->find('list', ['limit' => 200]);
        $users = $this->Publications->Users->find('list', ['limit' => 200]);
        $categories = $this->Publications->Categories->find('list', ['limit' => 200]);
        $tgroups = $this->Publications->Tgroups->find('list', ['limit' => 200]);
        $this->set(compact('publication', 'photos', 'typeOfPublications', 'users', 'categories', 'tgroups'));
    }

    /**
     * Delete method
     *
     * @param string|null $id Publication id.
     * @return \Cake\Http\Response|null Redirects to index.
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function delete($id = null)
    {
        $this->request->allowMethod(['post', 'delete']);
        $publication = $this->Publications->get($id);
        if ($this->Publications->delete($publication)) {
            $this->Flash->success(__('The publication has been deleted.'));
        } else {
            $this->Flash->error(__('The publication could not be deleted. Please, try again.'));
        }

        return $this->redirect(['action' => 'index']);
    }
}
