<?php
namespace App\Controller;

use App\Controller\AppController;
use Cake\Event\Event;
use App\Model\Table\UserGroupsTable;
use App\Model\Table\UsersTable;



/**
 * Tgroups Controller
 *
 * @property \App\Model\Table\TgroupsTable $Tgroups
 * * @property \App\Model\Table\UserGroupsTable $userGroup

 * @method \App\Model\Entity\Tgroup[]|\Cake\Datasource\ResultSetInterface paginate($object = null, array $settings = [])
 */
class TgroupsController extends AppController
{
    public function beforeFilter(Event $event)
    {
        $this->viewBuilder()->setLayout('forum');
        return parent::beforeFilter($event); // TODO: Change the autogenerated stub
    }

    /**
     * Index method
     *
     * @return \Cake\Http\Response|void
     */
    public function index()
    {

        $tgroups = $this->paginate($this->Tgroups->find()
            ->contain(['UserGroups'])
        );








        $this->set(compact('tgroups'));
    }

    /**
     * View method
     *
     * @param string|null $id Tgroup id.
     * @return \Cake\Http\Response|void
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function view($id = null)
    {
        $tgroup = $this->Tgroups->get($id, [
            'contain' => []
        ]);

        $this->set('tgroup', $tgroup);
    }

    /**
     * Add method
     *
     * @return \Cake\Http\Response|null Redirects on successful add, renders view otherwise.
     */
    public function add()
    {
        $tgroup = $this->Tgroups->newEntity();
        if ($this->request->is('post')) {
            $tgroup = $this->Tgroups->patchEntity($tgroup, $this->request->getData());
            if ($this->Tgroups->save($tgroup)) {
                $this->Flash->success(__('The tgroup has been saved.'));

                return $this->redirect(['action' => 'index']);
            }
            $this->Flash->error(__('The tgroup could not be saved. Please, try again.'));
        }
        $this->set(compact('tgroup'));
    }

    /**
     * Edit method
     *
     * @param string|null $id Tgroup id.
     * @return \Cake\Http\Response|null Redirects on successful edit, renders view otherwise.
     * @throws \Cake\Network\Exception\NotFoundException When record not found.
     */
    public function edit($id = null)
    {
        $tgroup = $this->Tgroups->get($id, [
            'contain' => []
        ]);
        if ($this->request->is(['patch', 'post', 'put'])) {
            $tgroup = $this->Tgroups->patchEntity($tgroup, $this->request->getData());
            if ($this->Tgroups->save($tgroup)) {
                $this->Flash->success(__('The tgroup has been saved.'));

                return $this->redirect(['action' => 'index']);
            }
            $this->Flash->error(__('The tgroup could not be saved. Please, try again.'));
        }
        $this->set(compact('tgroup'));
    }

    /**
     * Delete method
     *
     * @param string|null $id Tgroup id.
     * @return \Cake\Http\Response|null Redirects to index.
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function delete($id = null)
    {
        $this->request->allowMethod(['post', 'delete']);
        $tgroup = $this->Tgroups->get($id);
        if ($this->Tgroups->delete($tgroup)) {
            $this->Flash->success(__('The tgroup has been deleted.'));
        } else {
            $this->Flash->error(__('The tgroup could not be deleted. Please, try again.'));
        }

        return $this->redirect(['action' => 'index']);
    }
}
